#### G·ªôp Vietnam Airlines v√† Vietjet Air v√† G·ªôp 3 h√£ng th√†nh 1

In [3]:
# Ki·ªÉm tra c√≥ bao nhi√™u h√£ng bay 
unique_airlines = df_all['operating_airline_name'].dropna().unique()
print("S·ªë l∆∞·ª£ng h√£ng bay duy nh·∫•t trong 'operating_airline_name':", len(unique_airlines))
print("üõ´ Danh s√°ch c√°c h√£ng bay:")
print(unique_airlines)

S·ªë l∆∞·ª£ng h√£ng bay duy nh·∫•t trong 'operating_airline_name': 3
üõ´ Danh s√°ch c√°c h√£ng bay:
['Vietjet Air' 'VietNam Airlines' 'BAMBOO AIRWAYS']

### L·ªçc gi·ªØ l·∫°i c√°c c·ªôt c·∫ßn thi·∫øt

In [4]:
df_all.drop(columns=['source.name', 'departure_time', 'arrival_time', 'status'], inplace=True)
print("ƒê√£ x√≥a c√°c c·ªôt: source.name, departure_time, arrival_time, status kh·ªèi df_all.")

ƒê√£ x√≥a c√°c c·ªôt: source.name, departure_time, arrival_time, status kh·ªèi df_all.

In [5]:

print("üßæ C√°c c·ªôt hi·ªán c√≥ trong df_all:")
print(df_all.columns.tolist())

üßæ C√°c c·ªôt hi·ªán c√≥ trong df_all:
['date', 'route', 'flight_id', 'origin', 'destination', 'fare_class', 'fare_code', 'price_vnd', 'taxes', 'booking_class', 'cabin', 'quota', 'service_code', 'fare_conditions', 'operating_airline_code', 'operating_airline_name']

In [6]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2255788 entries, 0 to 2255787
Data columns (total 16 columns):
 #   Column                  Dtype
---  ------                  -----
 0   date                    object
 1   route                   object
 2   flight_id               object
 3   origin                  object
 4   destination             object
 5   fare_class              object
 6   fare_code               object
 7   price_vnd               float64
 8   taxes                   float64
 9   booking_class           object
 10  cabin                   object
 11  quota                   float64
 12  service_code            object
 13  fare_conditions         object
 14  operating_airline_code  object
 15  operating_airline_name  object
dtypes: float64(3), object(13)
memory usage: 275.4+ MB

In [7]:
# √âp ki·ªÉu c·ªôt date v·ªÅ datetime
df_all['date'] = pd.to_datetime(df_all['date'], errors='coerce')

In [8]:
# T·∫°o c·ªôt gi·ªù
df_all['hour'] = df_all['date'].dt.hour

# T·∫°o c·ªôt "kho·∫£ng th·ªùi gian bay"
def get_time_slot(hour):
    if 5 <= hour < 12:
        return 'S√°ng'
    elif 12 <= hour < 17:
        return 'Chi·ªÅu'
    elif 17 <= hour < 21:
        return 'T·ªëi'
    else:
        return 'ƒê√™m'

df_all['time_slot'] = df_all['hour'].apply(get_time_slot)

In [10]:
# ƒê·∫£m b·∫£o date ƒë√£ ƒë√∫ng ki·ªÉu datetime
df_all['date'] = pd.to_datetime(df_all['date'], errors='coerce')

# Th√™m c√°c c·ªôt th·ªùi gian
df_all['month'] = df_all['date'].dt.month
df_all['weekday'] = df_all['date'].dt.day_name()
df_all['week'] = df_all['date'].dt.isocalendar().week

In [15]:
df_all.info()
df_all

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2255788 entries, 0 to 2255787
Data columns (total 21 columns):
 #   Column                  Dtype
---  ------                  -----
 0   date                    datetime64[ns]
 1   route                   object
 2   flight_id               object
 3   origin                  object
 4   destination             object
 5   fare_class              object
 6   fare_code               object
 7   price_vnd               float64
 8   taxes                   float64
 9   booking_class           object
 10  cabin                   object
 11  quota                   float64
 12  service_code            object
 13  fare_conditions         object
 14  operating_airline_code  object
 15  operating_airline_name  object
 16  hour                    float64
 17  time_slot               object
 18  month                   float64
 19  weekday                 object
 20  week                    UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(5), object(14)
memory usage: 355.0+ MB

,date,route,flight_id,origin,destination,fare_class,fare_code,price_vnd,taxes,booking_class,cabin,quota,service_code,fare_conditions,operating_airline_code,operating_airline_name,hour,time_slot,month,weekday,week
0,2025-06-13,DLI_DAD,SEG-VJ568-DLIDAD-2025-1-01-1450,DLI,DAD,EL1,QPXVNWS,1.860040e+06,5.724264e+05,Z,ecoPremium,2.0,FBA4-C0FMC2,"PEN19,PEN20,PEN21",VJ,Vietjet Air,0.0,ƒê√™m,6.0,Friday,24
1,2025-06-13,DLI_DAD,SEG-VJ886-DLIDAD-2025-1-01-1450,DLI,DAD,EC1,ZVNWP,1.929579e+06,5.774921e+05,Z,ecoPremium,2.0,FBA4-C0FMC2,"PEN16,PEN17,PEN18",VJ,Vietjet Air,0.0,ƒê√™m,6.0,Friday,24
2,2025-06-13,DLI_DAD,SEG-VJ430-DLIDAD-2025-1-01-1450,DLI,DAD,EF1,ZVNWP,2.148786e+06,5.940708e+05,Z,ecoPremium,2.0,FBA4-C0FMC2,"PEN22,PEN23,PEN24",VJ,Vietjet Air,0.0,ƒê√™m,6.0,Friday,24
3,2025-06-13,DLI_DAD,SEG-VJ180-DLIDAD-2025-1-01-1450,DLI,DAD,DC1,ZVNWP,2.222009e+06,5.991365e+05,Z,ecoPremium,2.0,FBA4-C0FMC2,"PEN28,PEN29,PEN30",VJ,Vietjet Air,0.0,ƒê√™m,6.0,Friday,24
4,2025-06-13,DLI_DAD,SEG-VJ376-DLIDAD-2025-1-01-1450,DLI,DAD,DF1,ZVNWP,2.470690e+06,6.175573e+05,Z,ecoPremium,2.0,FBA4-C0FMC2,"PEN22,PEN23,PEN24",VJ,Vietjet Air,0.0,ƒê√™m,6.0,Friday,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255783,NaT,SGN_HAN,SEG-QH214-SGN_HAN-2026-01-02-1015,SGN,HAN,UEM0FW,EM1,3.372419e+06,1.265544e+06,L,eco,2.0,NaN,"PEN1,PEN2,PEN3",QH,BAMBOO AIRWAYS,NaN,ƒê√™m,NaN,NaN,<NA>
2255784,NaT,SGN_HAN,SEG-QH230-SGN_HAN-2026-01-02-745,SGN,HAN,LES0FW,ES1,2.747938e+06,8.145030e+05,M,eco,6.0,NaN,"PEN1,PEN2,PEN3",QH,BAMBOO AIRWAYS,NaN,ƒê√™m,NaN,NaN,<NA>
2255785,NaT,HAN_DLI,SEG-QH296-HAN_DLI-2026-01-02-1515,HAN,DLI,YEF0FW,ES13,4.557364e+06,1.261177e+06,N,eco,9.0,NaN,"PEN1,PEN2,PEN3",QH,BAMBOO AIRWAYS,NaN,ƒê√™m,NaN,NaN,<NA>
2255786,NaT,HAN_SGN,SEG-QH285-HAN_SGN-2026-01-02-1015,HAN,SGN,WEF0FW,ES1,4.195112e+06,1.224559e+06,W,eco,4.0,NaN,"PEN1,PEN2,PEN3",QH,BAMBOO AIRWAYS,NaN,ƒê√™m,NaN,NaN,<NA>
2255787,NaT,SGN_UIH,SEG-QH271-SGN_UIH-2026-01-02-845,SGN,UIH,LES0FW,ES1,2.862939e+06,8.135980e+05,W,eco,3.0,NaN,"PEN1,PEN2,PEN3",QH,BAMBOO AIRWAYS,NaN,ƒê√™m,NaN,NaN,<NA>

So s√°nh m·ª©c ch√™nh l·ªách gi√° theo h·∫°ng v√©

In [34]:

# Gi·∫£ s·ª≠ df_all l√† DataFrame ƒë√£ ƒë∆∞·ª£c g·ªôp s·∫µn t·ª´ c√°c file
# Ki·ªÉm tra c√°c c·ªôt c√≥ li√™n quan
print(df_all[['route', 'price_vnd', 'cabin', 'operating_airline_name', 'booking_class', 'fare_code', 'fare_conditions']].head())

# 1. So s√°nh ch√™nh l·ªách gi√° theo h·∫°ng v√© (Economy vs Business)
cabin_avg_price = df_all.groupby('cabin')['price_vnd'].mean().sort_values()
print("\n[1] Gi√° trung b√¨nh theo Cabin:\n", cabin_avg_price.apply(lambda x: f"{x:,.0f} VND"))

# 2. So s√°nh gi√° Economy/Business gi·ªØa c√°c h√£ng c√πng tuy·∫øn
cabin_airline_route = df_all.groupby(['route', 'cabin', 'operating_airline_name'])['price_vnd'].mean().reset_index()
pivot_price_compare = cabin_airline_route.pivot_table(index=['route', 'cabin'], 
                                                       columns='operating_airline_name', 
                                                       values='price_vnd')
print("\n[2] So s√°nh gi√° gi·ªØa c√°c h√£ng tr√™n c√πng tuy·∫øn (theo Cabin):\n", pivot_price_compare.applymap(lambda x: f"{x:,.0f} VND" if pd.notnull(x) else "-"))

     route     price_vnd       cabin operating_airline_name booking_class fare_code    fare_conditions
0  DLI_DAD  1.860040e+06  ecoPremium            Vietjet Air             Z   QPXVNWS  PEN19,PEN20,PEN21
1  DLI_DAD  1.929579e+06  ecoPremium            Vietjet Air             Z     ZVNWP  PEN16,PEN17,PEN18
2  DLI_DAD  2.148786e+06  ecoPremium            Vietjet Air             Z     ZVNWP  PEN22,PEN23,PEN24
3  DLI_DAD  2.222009e+06  ecoPremium            Vietjet Air             Z     ZVNWP  PEN28,PEN29,PEN30
4  DLI_DAD  2.470690e+06  ecoPremium            Vietjet Air             Z     ZVNWP  PEN22,PEN23,PEN24

[1] Gi√° trung b√¨nh theo Cabin:
 cabin
eco           3,175,016 VND
ecoPremium    4,384,022 VND
business      6,632,326 VND
Name: price_vnd, dtype: object

[2] So s√°nh gi√° gi·ªØa c√°c h√£ng tr√™n c√πng tuy·∫øn (theo Cabin):
 operating_airline_name BAMBOO AIRWAYS VietNam Airlines    Vietjet Air
route   cabin
CXR_DAD business                    -    8,159,514 VND  3,299,891 VND
        eco                         -    4,485,448 VND  1,812,551 VND
        ecoPremium                  -    6,250,365 VND  2,525,487 VND
CXR_DLI business                    -    7,246,208 VND  2,927,416 VND
        eco                         -    3,541,804 VND  1,431,242 VND
...                               ...              ...            ...
SGN_HAN ecoPremium                  -    4,608,437 VND  2,121,612 VND
SGN_UIH business        7,002,322 VND                -              -
        eco             2,987,039 VND                -              -
UIH_SGN business        6,351,017 VND                -              -
        eco             3,256,595 VND                -              -

[124 rows x 3 columns]

C:\Users\Nhat Canh\AppData\Local\Temp\ipykernel_21616\273469221.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print("\n[2] So s√°nh gi√° gi·ªØa c√°c h√£ng tr√™n c√πng tuy·∫øn (theo Cabin):\n", pivot_price_compare.applymap(lambda x: f"{x:,.0f} VND" if pd.notnull(x) else "-"))

In [28]:
# 3. Xem h√£ng n√†o gi√° t·ªët h∆°n cho t·ª´ng h·∫°ng
def better_price(row):
    values = row.dropna()
    if len(values) >= 2:
        return values.idxmin()
    return None

pivot_price_compare['Best_price_airline'] = pivot_price_compare.apply(better_price, axis=1)
print("\n[3] H√£ng c√≥ gi√° t·ªët nh·∫•t theo t·ª´ng tuy·∫øn v√† h·∫°ng:\n", pivot_price_compare[['Best_price_airline']])

# 4. Ph√¢n t√≠ch ƒë·ªô linh ho·∫°t (Booking_Class, Fare_Code, Fare_Conditions)
flex_analysis = df_all.groupby(['booking_class', 'fare_code', 'fare_conditions'])['price_vnd'].agg(['mean', 'count']).sort_values(by='mean')
print("\n[4] Ph√¢n t√≠ch ƒë·ªô linh ho·∫°t:\n", flex_analysis.head(10))  # hi·ªÉn th·ªã 10 d√≤ng ƒë·∫ßu

[3] H√£ng c√≥ gi√° t·ªët nh·∫•t theo t·ª´ng tuy·∫øn v√† h·∫°ng:
 operating_airline_name Best_price_airline
route   cabin
CXR_DAD business              Vietjet Air
        eco                   Vietjet Air
        ecoPremium            Vietjet Air
CXR_DLI business              Vietjet Air
        eco                   Vietjet Air
...                                   ...
SGN_HAN ecoPremium            Vietjet Air
SGN_UIH business                     None
        eco                          None
UIH_SGN business                     None
        eco                          None

[124 rows x 1 columns]

[4] Ph√¢n t√≠ch ƒë·ªô linh ho·∫°t:
                                                  mean  count
booking_class fare_code fare_conditions
A             AAP4VNWP  PEN1,PEN2,PEN3   6.988588e+05      8
P             PAP2VNWS  PEN1,PEN2,PEN3   9.341347e+05      7
R             RAP5VNWS  PEN1,PEN2,PEN3   1.122592e+06     16
P             PAP4VNWP  PEN1,PEN2,PEN3   1.144806e+06     79
E             EPXVNWS   PEN1,PEN2,PEN3   1.177843e+06   6533
N             NAP5VNWS  PEN1,PEN2,PEN3   1.181561e+06     10
R             RPXVNWP   PEN4,PEN5,PEN6   1.209763e+06    540
Q             QAP6VNWS  PEN1,PEN2,PEN3   1.239251e+06      2
R             RAP6VNWS  PEN1,PEN2,PEN3   1.241036e+06     18
P             PPXVNWS   PEN1,PEN2,PEN3   1.242406e+06      6

Nh·ªØng ng√†y c√≥ nhi·ªÅu chuy·∫øn bay nh·∫•t

In [20]:
# ƒê·∫£m b·∫£o c·ªôt ng√†y l√† d·∫°ng datetime
df_all['date'] = pd.to_datetime(df_all['date'])

# ƒê·∫øm s·ªë chuy·∫øn bay theo t·ª´ng ng√†y
flights_per_day = df_all['date'].value_counts().sort_values(ascending=False)

# Hi·ªÉn th·ªã top 10 ng√†y c√≥ nhi·ªÅu chuy·∫øn nh·∫•t
print("Top 10 ng√†y c√≥ nhi·ªÅu chuy·∫øn bay nh·∫•t:")
print(flights_per_day.head(10))

Top 10 ng√†y c√≥ nhi·ªÅu chuy·∫øn bay nh·∫•t:
date
2025-08-17    4829
2025-08-13    4774
2025-08-10    4752
2025-07-20    4745
2025-07-30    4738
2025-07-27    4720
2025-07-23    4718
2025-08-24    4688
2025-07-29    4684
2025-07-06    4675
Name: count, dtype: int64

In [36]:
# Trung b√¨nh gi√° v√© theo th√°ng
month_avg_price = df_all.groupby('month')['price_vnd'].mean().sort_values(ascending=False)

print("\n[3] Gi√° v√© trung b√¨nh theo th√°ng (gi·∫£m d·∫ßn):\n")
print(month_avg_price.apply(lambda x: f"{x:,.0f} VND"))

# Th√°ng c√≥ gi√° v√© trung b√¨nh cao nh·∫•t
max_month = month_avg_price.idxmax()
max_price = month_avg_price.max()

print(f"\nTh√°ng c√≥ gi√° v√© trung b√¨nh cao nh·∫•t: Th√°ng {max_month} v·ªõi m·ª©c gi√° trung b√¨nh: {max_price:,.0f} VND")

[3] Gi√° v√© trung b√¨nh theo th√°ng (gi·∫£m d·∫ßn):

month
2.0     3,995,363 VND
3.0     3,406,687 VND
4.0     3,349,370 VND
1.0     3,344,166 VND
5.0     3,333,594 VND
12.0    2,673,173 VND
11.0    2,665,188 VND
6.0     2,652,879 VND
10.0    2,608,576 VND
9.0     2,571,280 VND
8.0     2,564,037 VND
7.0     2,562,875 VND
Name: price_vnd, dtype: object

Th√°ng c√≥ gi√° v√© trung b√¨nh cao nh·∫•t: Th√°ng 2.0 v·ªõi m·ª©c gi√° trung b√¨nh: 3,995,363 VND

In [42]:
# Trung b√¨nh gi√° v√© theo th√°ng v√† h√£ng
monthly_airline_price = df_all.groupby(['operating_airline_name', 'month'])['price_vnd'].mean()

# T√¨m th√°ng c√≥ gi√° cao nh·∫•t cho m·ªói h√£ng
highest_month_per_airline = monthly_airline_price.groupby('operating_airline_name').idxmax()
highest_price_per_airline = monthly_airline_price.groupby('operating_airline_name').max()

# G·ªôp k·∫øt qu·∫£
result = pd.DataFrame({
    'Th√°ng cao nh·∫•t': highest_month_per_airline.map(lambda x: x[1]),
    'Gi√° trung b√¨nh cao nh·∫•t (VND)': highest_price_per_airline
})
result['Gi√° trung b√¨nh cao nh·∫•t (VND)'] = result['Gi√° trung b√¨nh cao nh·∫•t (VND)'].apply(lambda x: f"{x:,.0f}")
print("\nTh√°ng c√≥ gi√° v√© trung b√¨nh cao nh·∫•t theo t·ª´ng h√£ng:\n")
print(result)

Th√°ng c√≥ gi√° v√© trung b√¨nh cao nh·∫•t theo t·ª´ng h√£ng:

                        Th√°ng cao nh·∫•t Gi√° trung b√¨nh cao nh·∫•t (VND)
operating_airline_name
Vietjet Air                        2.0                     3,995,363

Trung b√¨nh gi√° v√© theo h√£ng, t√¨m h√£ng c√≥ gi√° v√© trung b√¨nh th·∫•p nh·∫•t

In [24]:
# T√≠nh trung b√¨nh gi√° v√© theo h√£ng bay
avg_price_by_airline = df_all.groupby("operating_airline_name")["price_vnd"].mean().sort_values()

# Hi·ªÉn th·ªã h√£ng c√≥ gi√° v√© trung b√¨nh r·∫ª nh·∫•t
print("H√£ng c√≥ gi√° v√© trung b√¨nh r·∫ª nh·∫•t:")
print(avg_price_by_airline.head(1).apply(lambda x: f"{x:,.0f} VND"))

# Hi·ªÉn th·ªã to√†n b·ªô ƒë·ªÉ so s√°nh
print("\nGi√° v√© trung b√¨nh theo t·ª´ng h√£ng:")
print(avg_price_by_airline.apply(lambda x: f"{x:,.0f} VND"))

H√£ng c√≥ gi√° v√© trung b√¨nh r·∫ª nh·∫•t:
operating_airline_name
Vietjet Air    2,792,002 VND
Name: price_vnd, dtype: object

Gi√° v√© trung b√¨nh theo t·ª´ng h√£ng:
operating_airline_name
Vietjet Air         2,792,002 VND
BAMBOO AIRWAYS      4,074,105 VND
VietNam Airlines    6,353,131 VND
Name: price_vnd, dtype: object

T√°c ƒë·ªông c·ªßa Booking Class v√† Fare Code ƒë·∫øn gi√°

In [23]:
avg_prices = df_all.groupby(['booking_class', 'fare_code'])["price_vnd"].mean().sort_values()
print(avg_prices.apply(lambda x: f"{x:,.0f} VND"))

booking_class  fare_code
A              AAP4VNWP       698,859 VND
P              PAP2VNWS       934,135 VND
               PAP4VNWP     1,207,625 VND
Q              QAP6VNWS     1,239,251 VND
P              PPXVNWS      1,242,406 VND
                                ...
J              IVNW         8,754,114 VND
Z              JVNW         8,765,676 VND
C              JVNWP        8,930,066 VND
               JVNW         9,097,492 VND
J              CVNW         9,272,827 VND
Name: price_vnd, Length: 851, dtype: object